"""create emails and email_attachments tables

Revision ID: 07bbe8764531
Revises: 
Create Date: 2026-03-06 10:22:18.175330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07bbe8764531'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=512), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('date_received', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emails_message_id'), ['message_id'], unique=True)

    op.create_table('email_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_attachments')
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_message_id'))

    op.drop_table('emails')
    # ### end Alembic commands ###
