"""add_searched_email_to_emails

Revision ID: c3a6b2a63242
Revises: b2c3d4e5f6a7
Create Date: 2026-03-07 12:18:39.113134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a6b2a63242'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('searched_email', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_emails_searched_email'), ['searched_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_searched_email'))
        batch_op.drop_column('searched_email')

    # ### end Alembic commands ###
